API_ID : 15395640
API_HASH : "342d15c979a8c8384cd42bdb49b1a424"
BOT_TOKEN : "6623936175:AAG9fBFQW4lZDZJvcH7m0OuZPZ-a0pQDsxg"
ADMINS : 
  - 509960032
  - 6543004696
  - 5361491365
MONGO_DB : "mongodb+srv://admin:pvsender64523@pvsender.p4x3bno.mongodb.net/?retryWrites=true&w=majority"
OWNER : "5361491365"
PANEL_URL : "https://b2.blackmeow.site"
API_URL : "https://sub.emamdad.site"
PANEL_USERNAME : "milad"
PANEL_PASSWORD : "milad64523."