START  : "گزینه مورد نظر خود را برای ادامه انتخاب کنید "
SUCCESS : "کاربر ساخته شد"
FAILED : "کاربر ساخته نشد"
ASK_USERNAME : "اسم کاربر رو وارد کن"
ASK_EXPIRE  : "تاریخ انقضا رو وارد کن"
ASK_TRAFFIC : "حجم کاربر رو انتخاب کن"
USER_PROFILE : "پروفایل کاربر : {}"
